apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: simulate-zone-failure
spec:
  entrypoint: zone-task
  templates:
  - name: zone-task
    script:
      image: python:3.10
      command: [python]
      source: |
        import rack_resiliency_test
        rack_resiliency_test.simulate_random_zone_failure()
