apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: simulate-node-failure
spec:
  entrypoint: node-task
  templates:
  - name: node-task
    script:
      image: python:3.10
      command: [python]
      source: |
        import rack_resiliency_test
        rack_resiliency_test.simulate_random_node_failure()
