apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
  labels:
    app: etcd-sim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd-sim
  template:
    metadata:
      labels:
        app: etcd-sim
    spec:
      containers:
      - name: etcd-sim
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo etcd service running; sleep 10; done"]
