apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: rr-rack-cycle
  namespace: argo
spec:
  serviceAccountName: argo-workflow

  # Set the default node selector for all templates in the workflow
  nodeSelector:
    kubernetes.io/hostname: master-m003

  ttlStrategy:
    secondsAfterCompletion: 3600

  podGC:
    strategy: OnWorkflowCompletion

  entrypoint: rr-rack-dag

  templates:
  - name: rr-rack-dag
    dag:
      tasks:

      - name: pre-health-check
        template: invoke-python
        arguments:
          parameters:
          - name: action
            value: "health-check"

      - name: simulate-rack
        dependencies: [pre-health-check]
        template: invoke-python
        arguments:
          parameters:
          - name: action
            value: "simulate-rack"

      - name: post-health-check
        dependencies: [simulate-rack]
        template: invoke-python
        arguments:
          parameters:
          - name: action
            value: "health-check"

  - name: invoke-python
    inputs:
      parameters:
      - name: action
    container:
      image: kushsahni1/chaos-sim:latest
      imagePullPolicy: Always
      
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
      
      command:
      - python3
      - /app/rack_resiliency_to_host.py
      args:
      - "{{inputs.parameters.action}}"
      env:
      - name: KUBECONFIG
        value: /home/argo/.kube/config
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

      volumeMounts:
      - name: log-vol
        mountPath: /app/logs

    # Explicitly setting nodeSelector at template level as well
    nodeSelector:
      kubernetes.io/hostname: master-m003

    tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

    volumes:
    - name: log-vol
      hostPath:
        path: /home/vagrant/argo-logs/rr-rack-cycle
        type: DirectoryOrCreate 
